version: 2
updates:
  # Check daily for updates to npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@inlang/*"
  # Check daily for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gh-actions:
        patterns:
          - "*"
