version: 2
updates:
  # Check weekly for updates to npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
